targets:
  $default:
    sources:
      - lib/**
      - config/**
      - config.yaml
    builders:
      mayr_config|mayr_config_builder:
        enabled: true

builders:
  mayr_config_builder:
    import: "package:mayr_config/src/generator.dart"
    builder_factories: ["mayrConfigBuilder"]
    build_extensions: {".yaml": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: []
    defaults:
      generate_for:
        - config/**
        - config.yaml
