targets:
  $default:
    builders:
      mayr_config|mayr_config_builder:
        enabled: true

builders:
  mayr_config_builder:
    import: "package:mayr_config/src/generator.dart"
    builder_factories: ["mayrConfigBuilder"]
    build_extensions: {r"$lib$": [".g.dart"]}
    auto_apply: dependents
    build_to: source
